services:
  
  pg:
    image: postgres:16.3-alpine
    container_name: pg
    environment:
      POSTGRES_DB: hf_demo
      POSTGRES_USER: hf_user
      POSTGRES_PASSWORD: 3FWE$43xwq@dA
    ports:
      - 55432:5432
    volumes:
     - pg-data:/var/lib/postgresql/data
    networks:
      - si-base-x-network

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pg-admin
    ports:
     - 55433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pga-data:/var/lib/pgadmin
    depends_on:
      - pg
    networks:
      - si-base-x-network

networks:
  hf-demo:

volumes:
  pg-data:
  pga-data:
