services:

  api:
    image: hf-demo-api:latest
    container_name: hf-demo-api
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - 55400:8080
    networks:
      - hf-demo
    depends_on:
      - pg
    environment:
      Hangfire__Database__Host: pg
      Hangfire__Database__Port: 5432
      Hangfire__Database__Name: hf_demo
      Hangfire__Database__User: hf_user
      Hangfire__Database__Password: 3FWE$43xwq@dA
  
  server.blue:
    image: hf-demo-server:latest
    container_name: hf-demo-server-blue
    build:
      context: .
      dockerfile: server.dockerfile
    networks:
      - hf-demo
    depends_on:
      - pg
    environment:
      Hangfire__Database__Host: pg
      Hangfire__Database__Port: 5432
      Hangfire__Database__Name: hf_demo
      Hangfire__Database__User: hf_user
      Hangfire__Database__Password: 3FWE$43xwq@dA
      Hangfire__Queues__0: blue

  server.green:
    image: hf-demo-server:latest
    container_name: hf-demo-server-green
    build:
      context: .
      dockerfile: server.dockerfile
    networks:
      - hf-demo
    depends_on:
      - pg
    environment:
      Hangfire__Database__Host: pg
      Hangfire__Database__Port: 5432
      Hangfire__Database__Name: hf_demo
      Hangfire__Database__User: hf_user
      Hangfire__Database__Password: 3FWE$43xwq@dA
      Hangfire__Queues__0: green

  server.green-blue:
    image: hf-demo-server:latest
    container_name: hf-demo-server-green-blue
    build:
      context: .
      dockerfile: server.dockerfile
    networks:
      - hf-demo
    depends_on:
      - pg
    environment:
      Hangfire__Database__Host: pg
      Hangfire__Database__Port: 5432
      Hangfire__Database__Name: hf_demo
      Hangfire__Database__User: hf_user
      Hangfire__Database__Password: 3FWE$43xwq@dA
      Hangfire__Queues__0: green
      Hangfire__Queues__1: blue
  
  pg:
    image: postgres:16.3-alpine
    container_name: pg
    hostname: pg
    environment:
      POSTGRES_DB: hf_demo
      POSTGRES_USER: hf_user
      POSTGRES_PASSWORD: 3FWE$43xwq@dA
    ports:
      - 55432:5432
    volumes:
     - pg-data:/var/lib/postgresql/data
    networks:
      - hf-demo

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pg-admin
    ports:
     - 55433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pga-data:/var/lib/pgadmin
    depends_on:
      - pg
    networks:
      - hf-demo

networks:
  hf-demo:

volumes:
  pg-data:
  pga-data:
